name: Post NFT to Zora Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:     

jobs:
  coin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd Backend && npm install

      - name: Run TypeScript bot
        run: cd Backend && npx tsx main.ts
        env:
          PINATA_JWT: ${{ secrets.PINATA_JWT }}
          GATEWAY_URL: ${{ secrets.GATEWAY_URL }}
          ZORA_KEY: ${{ secrets.ZORA_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          WEB_HOOK: ${{ secrets.WEB_HOOK }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY}}
